version: '3.8'

name: jumbo-java
services:
  teamcity-database:
    container_name: teamcity-database
    image: postgres:${POSTGRES_VERSION}
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - teamcity-database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  teamcity-server:
    container_name: teamcity-server
    image: jetbrains/teamcity-server:${TEAMCITY_VERSION}
    ports:
      - "8111:8111"
    volumes:
      - teamcity-data:/data/teamcity_server/datadir
      - teamcity-logs:/opt/teamcity/logs
    depends_on:
      - teamcity-database

  teamcity-agent-47:
    container_name: teamcity-agent-47
    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION}
    privileged: true
    volumes:
      - teamcity-agent-47-conf:/data/teamcity_agent/conf
    environment:
      SERVER_URL: ${SERVER_URL}
      DOCKER_IN_DOCKER: start
      AGENT_NAME: agent_47

volumes:
  teamcity-database:
    name: teamcity-database
  teamcity-agent-47-conf:
    name: teamcity-agent-47-conf
  teamcity-data:
    name: teamcity-server-data
  teamcity-logs:
    name: teamcity-server-logs